#!/bin/bash
#Skripti algus, tegija Maldis-Sveno Laur
#Kõigepealt see skript väljastab kasutajale menüü
echo "1) steak and potatoes"
echo "2) fish and chips"
echo "3) soup and salad"
#küsib kasutajalt, et teeks valiku antud menüüst
echo "Please make a selection (1 or 2 or 3): "
read vastus
#kui valib valiku 1, siis kuvab kirjelduse
if [ "$vastus" = "1" ]; then
echo "Stick to your ribs."
echo "Watch your cholesterol."
echo "Enjoy your meal!"
#kui valib valiku 2, siis kuvab kirjelduse
elif [ "$vastus" = "2" ]; then
echo "British are coming!"
echo "Enjoy your meal!"
#kui valib valiku3, siis kuvab järgneva kirjelduse
elif [ "$vastus" = "3" ]; then
echo "Health foods..."
echo "Dieting is so boring."
echo "Enjoy your meal!"
#juhul kui valib muu numbri, siis vastab
else echo "Palun kasuta valikut 1-3"
fi
