#!/bin/bash
# Skript joonistab roopkyliku, mis koosneb sisestatud ridade arvust
echo -n "Sisesta ridade arv: "
read arv
#loeb ridade arvu
for ((r=1; r<$arv+1; r++))
do
echo -n "$r "
#tühikute loop
for (( v=1; v<$(($arv+1-$r+1)); v++))
	do
		echo -n " "
done
#tärnide loop
for (( i = $arv; i <= $arv; i++ ))
do
	for (( j = 1 ; j <= i ; j++ ))
	do
		echo -n "* "
	done
done
#reavahetus - skripti lõpus
echo ""
done
