#!/bin/bash
#
#Maja katusega
#
for((r=1; r<7; r++))
do
#trükime reanumbri ilma reavhaetuseta
#	echo -n "$r "
	for((v=1; v<$((6-$r+1)); v++))
	do
	#tärnid
	echo -n "  "
	done
	 #tuleb lisada o-d
	 for((v=1; v<$r; v++))
	 do
	 echo -n "+ "
	 done
#lisame plussid
        	for((v=1; v<$(($r+1)); v++))
        	do
		echo -n "+ "
		done
	#kui rida lõpeb - reavahetus
	echo
done
#
for (( i = 1; i <= 5; i++ ))      ### Outer for loop ###
do
echo -n "  "
echo -n "+ "
    for ((j=2 ; j<9; j++ )) ### Inner for loop ###
    do
          echo -n "o "
    done
echo -n "+ "
  echo "" #### print the new line ###
done


