#!/bin/bash
#
# poolik kolmnurk vasakult paremale
#
for((r=5; r>0; r--))
do
#trükime reanumbri ilma reavhaetuseta
#	echo -n $r
	for((v=1; v<=$r; v++))
	do
	#tärnid
	echo -n "* "
	done
	#kui rida lõpeb - reavahetus
	echo
done
