#!/bin/bash
#
# poolik kolmnurk  paremalt vasakule, numbrid tagurpidi
#
for((r=1; r<6; r++))
do
#trükime reanumbri ilma reavhaetuseta
	echo -n "$r "
	for((v=1; v<$((6-$r+1)); v++))
	do
	#tärnid
	echo -n "* "
	done
	#kui rida lõpeb - reavahetus
	echo
done
