#!/bin/bash
#
#10-ne arvu välja kirjutamine
#
summa=0
for(( i=1;i<=10;i++ ))
do
	echo $i
	jaak=$(($i%2))
	if [ $jaak -eq 0 ]; then
		summa=$(( $summa+$i ))
	fi
done
echo "Paarisarvude summa on:$summa"
