#!/bin/bash
#pingimine IP_range 172.23.13.20-172.23.13.40

for ip in 172.23.13.{20..50}
do
	#ping $ip -c 1 -f voib seda kasutada ka
	ping $ip -c 1 > /dev/null
	if [ $? -eq 0 ]; then
		echo "$ip - OK"
	else
		echo "$ip - NOT OK"
	fi
done
